### ISSUE TITLE
Translation to webpage

### ISSUE THREAD

**Issue by Almeonamy** [BogdanovKirill/RtspClientSharp#1]
Hello. How can I receive video stream on backed of website and push it to webpage?

**Comment by Almeonamy** [comment]
And how can I save this stream in the file?

**Comment by BogdanovKirill** [comment]
@Almeonamy 

For streaming to web page you need to encode frame streams from RtspClientSharp to something like HLS/MPEG-DASH. I dont have out of the box solution for you, it's really difficult story. It seems that you could use FFmpeg library to pack video/audio to HLS.

You could save stream from RtspClientSharp to your own binary format. For example you want to save JPEG stream from camera:
```csharp
//first create file where you will save your frames
var fs = new FileStream("S:\\archive.bin", FileMode.Create);
//then use RTSP client
using (var rtspClient = new RtspClient(connectionParameters))
{
  rtspClient.FrameReceived += RtspClientOnFrameReceived;

  await rtspClient.ConnectAsync(token);
  await rtspClient.ReceiveAsync(token);
}

private static void RtspClientOnFrameReceived(object sender, RawFrame e)
{
    if (e is RawJpegFrame rawJpegFrame)
    {
         byte[] frameSizeBytes = BitConverter.GetBytes(rawJpegFrame.FrameSegment.Count);
          //here we are writing frame's total size
         fs.Write(frameSizeBytes, 0, frameSizeBytes.Length);
         //and then all frame's bytes
         fs.Write(rawJpegFrame.FrameSegment.Array, rawJpegFrame.FrameSegment.Offset, rawJpegFrame.FrameSegment.Count);
    }
 }
```
later you could read you archive file like that:
```csharp
byte[] frameSizeBytes = new byte[4];
fs.Read(frameSizeBytes, 0, frameSizeBytes.Length);
int frameSize = BitConverter.ToInt32(frameSizeBytes, 0);
byte[] frameBuffer = new byte[frameSize];
fs.Read(frameBuffer, 0, frameSize);

var frame = new RawJpegFrame(DateTime.UtcNow, new ArraySegment<byte>(frameBuffer));
```
Ofcourse, in production code you don't have to reallocate bytes for every frame. The right way is to reuse buffers always when it's possible. Also we should always check return value of Read method of FileStream.

BTW, you could save every JPEG frame in separate file and then open it in any viewer as usually. But you should understand that this could work efficent only for rare snapshots (e.g. 1 snapshot per minute/30 minutes/hour).

**Comment by Almeonamy** [comment]
Ok, thanks
