### ISSUE TITLE
Can only receive RawAACFrame, no video

### ISSUE THREAD

**Issue by jdluzen** [BogdanovKirill/RtspClientSharp#10]
*Thank you for this great project!*

**Describe the bug**
Cannot receive video frames, only audio.

**To Reproduce**
```
            using (RtspClient client = new RtspClient(new ConnectionParameters(new Uri("rtsp://192.168.1.xxx:yyy/theCorrectUrl"))
            {
                RequiredTracks = RequiredTracks.All,
                RtpTransport = RtpTransportProtocol.TCP
            }))
```

**Expected behavior**
I expect to see interleaved audio and video frames, but I only see `RawAACFrame`.

**Screenshots**
```
RawAACFrame (243): 11/24/2018 19:11:00
RawAACFrame (266): 11/24/2018 19:11:00
RawAACFrame (247): 11/24/2018 19:11:01
RawAACFrame (245): 11/24/2018 19:11:01
RawAACFrame (233): 11/24/2018 19:11:01
RawAACFrame (250): 11/24/2018 19:11:01
RawAACFrame (246): 11/24/2018 19:11:01
RawAACFrame (245): 11/24/2018 19:11:01
RawAACFrame (232): 11/24/2018 19:11:01
RawAACFrame (265): 11/24/2018 19:11:02
RawAACFrame (251): 11/24/2018 19:11:02
RawAACFrame (252): 11/24/2018 19:11:02
RawAACFrame (250): 11/24/2018 19:11:02
RawAACFrame (249): 11/24/2018 19:11:02
RawAACFrame (252): 11/24/2018 19:11:02
RawAACFrame (247): 11/24/2018 19:11:02
RawAACFrame (243): 11/24/2018 19:11:02
RawAACFrame (263): 11/24/2018 19:11:03
RawAACFrame (246): 11/24/2018 19:11:03
RawAACFrame (245): 11/24/2018 19:11:03
RawAACFrame (249): 11/24/2018 19:11:03
RawAACFrame (259): 11/24/2018 19:11:03
RawAACFrame (243): 11/24/2018 19:11:03
RawAACFrame (248): 11/24/2018 19:11:03
RawAACFrame (250): 11/24/2018 19:11:03
RawAACFrame (245): 11/24/2018 19:11:04
RawAACFrame (242): 11/24/2018 19:11:04
RawAACFrame (243): 11/24/2018 19:11:04
```

**Desktop (please complete the following information):**
 - Win 10x64
 - Version 1.2.4

**Additional context**
VLC correctly plays both AAC audio and H.264 video with the same URL. I will attempt to get the source and debug.

**Comment by jdluzen** [comment]
It may have something to do with `H264Parser._waitForIFrame`.

**Comment by jdluzen** [comment]
After learning tons about H.264, it seems that my particular encoder sequences the `nalUnitType`s like so: `787111...7...[111...7]...`.

**Comment by BogdanovKirill** [comment]
@jdluzen

Thank you for your feedback. Is it possible to give me access to such camera ? I want to research.

**Comment by BogdanovKirill** [comment]
Any news? Reopen if you need.

**Comment by zhuzwing** [comment]
I also have this problem here. How to solve it?

**Comment by theateist** [comment]
I also have this problem. Can anyone explain how to solve this?

**Comment by dagrooms52** [comment]
Same problem. I can open the RTSP stream in VLC, but only get audio frames using this client library. I can provide the video if needed.

**Comment by emoo44566** [comment]
Same problem
