### ISSUE TITLE
x64 libffmpeghelper.dll An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by solonm** [BogdanovKirill/RtspClientSharp#101]
Hi @BogdanovKirill thank you so much for this project.

I am working on a project that uses you **FFmpegVideoPInvoke** which in turn uses the **libffmpeghelper.dll**.
I have another library that is only for 64 bit so i need to have all my projects building for x64.
I added the dll's from the x64 directory in the bin and when it calls the **CreateVideoDecoder** method it throws the exception:
**System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'**

![image](https://user-images.githubusercontent.com/5469407/98738428-560f6d80-23b0-11eb-9a69-66ddeaaade2b.png)

If I have my project pointing on x86 this works as expected.

**Please let me know if there is anything else i can check or if someone got the x64 dll to work on their project.**

**Desktop (please complete the following information):**
 - OS: Windows 10

Thanks

**Comment by solonm** [comment]
I just managed to rebuild the libffmpeghelper project to x64 and it worked as expected. 
Not sure if there is a problem with the provided dlls

**Comment by jaydubal** [comment]
Hello @solonm can you please provide your "libffmpeghelper.dll" / x64? thanks.
