### ISSUE TITLE
HTTP Transport?

### ISSUE THREAD

**Issue by MrZander** [BogdanovKirill/RtspClientSharp#11]
The readme suggests that this supports RTSP over HTTP, but only TCP and UDP are available in the RtpTransportProtocol enum.

How do you do HTTP transport?

**Comment by BogdanovKirill** [comment]
> The readme suggests that this supports RTSP over HTTP, but only TCP and UDP are available in the RtpTransportProtocol enum.
> 
> How do you do HTTP transport?

Yes, you could only select transport for RTP protocol, not RTSP. 
Just change rtsp:// prefix in your address to http:// prefix to connect over HTTP.

**Comment by MrZander** [comment]
Okay thanks, that is what I tried, turns out my camera system is just garbage and doesn't implement RTSP properly.  Thanks!
