### ISSUE TITLE
anyone have libffmpeghelper for x64 ?

### ISSUE THREAD

**Issue by ftjellal** [BogdanovKirill/RtspClientSharp#13]
I try to build libffmpeghelper in x64 but fail

can anyone teach me or give me libffmpeghelper.dll for x64

thx.

**Comment by BogdanovKirill** [comment]
Hello,

I plan to do it. You only need LIB files for x64

**Comment by ftjellal** [comment]
Ok. thanks. 

I will try to compile with lib x64. ^_^

**Comment by OptivolveAtila** [comment]
> Ok. thanks.
> 
> I will try to compile with lib x64. ^_^

Hi, I have problem too when to build libffmpeghelper in x64. Have you solve it?

**Comment by ftjellal** [comment]
> > Ok. thanks.
> > I will try to compile with lib x64. ^_^
> 
> Hi, I have problem too when to build libffmpeghelper in x64. Have you solve it?

Sry for late replied. I changed lib in RtspClientSharp/Examples/libffmpeghelper/include/ to x64 files and complied again. I don't know there was the true solution but my libffmpeghelper.dll can run in x64 system.

This is my dll. https://drive.google.com/file/d/1bcAf5jDLEYF9C_FHeyGlTnCEOX8xpcb8/view

**Comment by OptivolveAtila** [comment]
> > > Ok. thanks.
> > > I will try to compile with lib x64. ^_^
> > 
> > 
> > Hi, I have problem too when to build libffmpeghelper in x64. Have you solve it?
> 
> Sry for late replied. I changed lib in RtspClientSharp/Examples/libffmpeghelper/include/ to x64 files and complied again. I don't know there was the true solution but my libffmpeghelper.dll can run in x64 system.
> 
> This is my dll. https://drive.google.com/file/d/1bcAf5jDLEYF9C_FHeyGlTnCEOX8xpcb8/view

Thanks a lot @ftjellal! I'll try to run on my local

**Comment by BogdanovKirill** [comment]
Hi all,

I've added X64 libraries to master branch. You could choose platform to build in solution. Please check.

**Comment by jaydubal** [comment]
Hello @BogdanovKirill  the "libffmpeghelper.dll" is missing in the "x64" folder. Thanks!
Is it possible to have the compiled version / x64.
