### ISSUE TITLE
Problem when connect with 2 IP cameras

### ISSUE THREAD

**Issue by ftjellal** [BogdanovKirill/RtspClientSharp#14]
I tried to connect 2 camera by using example from RTSPPlayer. 

I change function ConnectAsync to ConnectAsyncFront and ConnectAsyncTop for front and top camera.

but in FrameReceived event I sometimes get frame from another camera.

hear is my some code

```
private async Task ConnectAsyncFront(ConnectionParameters connectionParameters, CancellationToken token)
        {
            try
            {
                TimeSpan delay = TimeSpan.FromSeconds(5);
                using (var rtspClientFront = new RtspClient(connectionParameters))
                {
                    rtspClientFront.FrameReceived +=
                        (sender, rawFrame) =>
                        {
                            if (!(rawFrame is RawVideoFrame rawVideoFrame))
                                return;
                            FFmpegVideoDecoder decoder = GetDecoderForFrame(rawVideoFrame);

                            if (!decoder.TryDecode(rawVideoFrame, out DecodedVideoFrameParameters decodedFrameParameters))
                                return;

                            int targetWidth;
                            int targetHeight;

                            int bufferSize;

                            targetWidth = decodedFrameParameters.Width;
                            targetHeight = decodedFrameParameters.Height;

                            bufferSize = decodedFrameParameters.Height *
                                         ImageUtils.GetStride(decodedFrameParameters.Width, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24);


                            var bufferSegment = new ArraySegment<byte>(new byte[bufferSize]);

                            var postVideoDecodingParameters = new PostVideoDecodingParameters(RectangleF.Empty,
                                new Size(targetWidth, targetHeight),
                                ScalingPolicy.Stretch, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24, ScalingQuality.Bicubic);
                            IDecodedVideoFrame decodedFrame = decoder.GetDecodedFrame(bufferSegment, postVideoDecodingParameters);
                            byte[] a = decodedFrame.DecodedBytes.ToArray<byte>();
                            var b = new Bitmap(decodedFrame.Width, decodedFrame.Height, decodedFrame.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, Marshal.UnsafeAddrOfPinnedArrayElement(a, 0));
                            gFront.DrawImage(new Bitmap(b, new Size(panelFront.Width, panelFront.Height)), new Point(0, 0));
                            picFront = new Bitmap((Bitmap)b.Clone());
                        };

                    while (true)
                    {
                        Console.WriteLine("Connecting...");

                        try
                        {
                            await rtspClientFront.ConnectAsync(token);
                        }
                        catch (OperationCanceledException)
                        {
                            return;
                        }
                        catch (RtspClientException e)
                        {
                            Console.WriteLine(e.ToString());
                            await Task.Delay(delay, token);
                            continue;
                        }

                        Console.WriteLine("Connected.");

                        try
                        {
                            await rtspClientFront.ReceiveAsync(token);
                        }
                        catch (OperationCanceledException)
                        {
                            return;
                        }
                        catch (RtspClientException e)
                        {
                            Console.WriteLine(e.ToString());
                            await Task.Delay(delay, token);
                        }
                    }
                }
            }
            catch (OperationCanceledException)
            {
            }
        }

private async Task ConnectAsyncTop(ConnectionParameters connectionParameters, CancellationToken token)
        {
            try
            {
                TimeSpan delay = TimeSpan.FromSeconds(5);

                using (var rtspClientTop = new RtspClient(connectionParameters))
                {
                    rtspClientTop.FrameReceived +=
                        (sender, rawFrame) =>
                        {
                            if (!(rawFrame is RawVideoFrame rawVideoFrame))
                                return;
                            FFmpegVideoDecoder decoder = GetDecoderForFrame(rawVideoFrame);

                            if (!decoder.TryDecode(rawVideoFrame, out DecodedVideoFrameParameters decodedFrameParameters))
                                return;

                            int targetWidth;
                            int targetHeight;

                            int bufferSize;

                                targetWidth = decodedFrameParameters.Width;
                                targetHeight = decodedFrameParameters.Height;

                                bufferSize = decodedFrameParameters.Height *
                                             ImageUtils.GetStride(decodedFrameParameters.Width, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24);


                            var bufferSegment = new ArraySegment<byte>(new byte[bufferSize]);

                            var postVideoDecodingParameters = new PostVideoDecodingParameters(RectangleF.Empty,
                                new Size(targetWidth, targetHeight),
                                ScalingPolicy.Stretch, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24, ScalingQuality.Bicubic);
                            IDecodedVideoFrame decodedFrame = decoder.GetDecodedFrame(bufferSegment, postVideoDecodingParameters);
                            byte[] a = decodedFrame.DecodedBytes.ToArray<byte>();
                            var b = new Bitmap(decodedFrame.Width, decodedFrame.Height, decodedFrame.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, Marshal.UnsafeAddrOfPinnedArrayElement(a, 0));
                            gTop.DrawImage(new Bitmap(b, new Size(panelTop.Width, panelTop.Height)), new Point(0, 0));
                            picTop = new Bitmap((Bitmap)b.Clone());
                        };

                    while (true)
                    {
                        Console.WriteLine("Connecting...");

                        try
                        {
                            await rtspClientTop.ConnectAsync(token);
                        }
                        catch (OperationCanceledException)
                        {
                            return;
                        }
                        catch (RtspClientException e)
                        {
                            Console.WriteLine(e.ToString());
                            await Task.Delay(delay, token);
                            continue;
                        }

                        Console.WriteLine("Connected.");

                        try
                        {
                            await rtspClientTop.ReceiveAsync(token);
                        }
                        catch (OperationCanceledException)
                        {
                            return;
                        }
                        catch (RtspClientException e)
                        {
                            Console.WriteLine(e.ToString());
                            await Task.Delay(delay, token);
                        }
                    }
                }
            }
            catch (OperationCanceledException)
            {
            }
        }
```

**Comment by BogdanovKirill** [comment]
> I tried to connect 2 camera by using example from RTSPPlayer.
> 
> I change function ConnectAsync to ConnectAsyncFront and ConnectAsyncTop for front and top camera.
> 
> but in FrameReceived event I sometimes get frame from another camera.
> 
> hear is my some code
> 
> ```
> private async Task ConnectAsyncFront(ConnectionParameters connectionParameters, CancellationToken token)
>         {
>             try
>             {
>                 TimeSpan delay = TimeSpan.FromSeconds(5);
>                 using (var rtspClientFront = new RtspClient(connectionParameters))
>                 {
>                     rtspClientFront.FrameReceived +=
>                         (sender, rawFrame) =>
>                         {
>                             if (!(rawFrame is RawVideoFrame rawVideoFrame))
>                                 return;
>                             FFmpegVideoDecoder decoder = GetDecoderForFrame(rawVideoFrame);
> 
>                             if (!decoder.TryDecode(rawVideoFrame, out DecodedVideoFrameParameters decodedFrameParameters))
>                                 return;
> 
>                             int targetWidth;
>                             int targetHeight;
> 
>                             int bufferSize;
> 
>                             targetWidth = decodedFrameParameters.Width;
>                             targetHeight = decodedFrameParameters.Height;
> 
>                             bufferSize = decodedFrameParameters.Height *
>                                          ImageUtils.GetStride(decodedFrameParameters.Width, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24);
> 
> 
>                             var bufferSegment = new ArraySegment<byte>(new byte[bufferSize]);
> 
>                             var postVideoDecodingParameters = new PostVideoDecodingParameters(RectangleF.Empty,
>                                 new Size(targetWidth, targetHeight),
>                                 ScalingPolicy.Stretch, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24, ScalingQuality.Bicubic);
>                             IDecodedVideoFrame decodedFrame = decoder.GetDecodedFrame(bufferSegment, postVideoDecodingParameters);
>                             byte[] a = decodedFrame.DecodedBytes.ToArray<byte>();
>                             var b = new Bitmap(decodedFrame.Width, decodedFrame.Height, decodedFrame.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, Marshal.UnsafeAddrOfPinnedArrayElement(a, 0));
>                             gFront.DrawImage(new Bitmap(b, new Size(panelFront.Width, panelFront.Height)), new Point(0, 0));
>                             picFront = new Bitmap((Bitmap)b.Clone());
>                         };
> 
>                     while (true)
>                     {
>                         Console.WriteLine("Connecting...");
> 
>                         try
>                         {
>                             await rtspClientFront.ConnectAsync(token);
>                         }
>                         catch (OperationCanceledException)
>                         {
>                             return;
>                         }
>                         catch (RtspClientException e)
>                         {
>                             Console.WriteLine(e.ToString());
>                             await Task.Delay(delay, token);
>                             continue;
>                         }
> 
>                         Console.WriteLine("Connected.");
> 
>                         try
>                         {
>                             await rtspClientFront.ReceiveAsync(token);
>                         }
>                         catch (OperationCanceledException)
>                         {
>                             return;
>                         }
>                         catch (RtspClientException e)
>                         {
>                             Console.WriteLine(e.ToString());
>                             await Task.Delay(delay, token);
>                         }
>                     }
>                 }
>             }
>             catch (OperationCanceledException)
>             {
>             }
>         }
> 
> private async Task ConnectAsyncTop(ConnectionParameters connectionParameters, CancellationToken token)
>         {
>             try
>             {
>                 TimeSpan delay = TimeSpan.FromSeconds(5);
> 
>                 using (var rtspClientTop = new RtspClient(connectionParameters))
>                 {
>                     rtspClientTop.FrameReceived +=
>                         (sender, rawFrame) =>
>                         {
>                             if (!(rawFrame is RawVideoFrame rawVideoFrame))
>                                 return;
>                             FFmpegVideoDecoder decoder = GetDecoderForFrame(rawVideoFrame);
> 
>                             if (!decoder.TryDecode(rawVideoFrame, out DecodedVideoFrameParameters decodedFrameParameters))
>                                 return;
> 
>                             int targetWidth;
>                             int targetHeight;
> 
>                             int bufferSize;
> 
>                                 targetWidth = decodedFrameParameters.Width;
>                                 targetHeight = decodedFrameParameters.Height;
> 
>                                 bufferSize = decodedFrameParameters.Height *
>                                              ImageUtils.GetStride(decodedFrameParameters.Width, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24);
> 
> 
>                             var bufferSegment = new ArraySegment<byte>(new byte[bufferSize]);
> 
>                             var postVideoDecodingParameters = new PostVideoDecodingParameters(RectangleF.Empty,
>                                 new Size(targetWidth, targetHeight),
>                                 ScalingPolicy.Stretch, SimpleRtspPlayer.RawFramesDecoding.PixelFormat.Bgr24, ScalingQuality.Bicubic);
>                             IDecodedVideoFrame decodedFrame = decoder.GetDecodedFrame(bufferSegment, postVideoDecodingParameters);
>                             byte[] a = decodedFrame.DecodedBytes.ToArray<byte>();
>                             var b = new Bitmap(decodedFrame.Width, decodedFrame.Height, decodedFrame.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, Marshal.UnsafeAddrOfPinnedArrayElement(a, 0));
>                             gTop.DrawImage(new Bitmap(b, new Size(panelTop.Width, panelTop.Height)), new Point(0, 0));
>                             picTop = new Bitmap((Bitmap)b.Clone());
>                         };
> 
>                     while (true)
>                     {
>                         Console.WriteLine("Connecting...");
> 
>                         try
>                         {
>                             await rtspClientTop.ConnectAsync(token);
>                         }
>                         catch (OperationCanceledException)
>                         {
>                             return;
>                         }
>                         catch (RtspClientException e)
>                         {
>                             Console.WriteLine(e.ToString());
>                             await Task.Delay(delay, token);
>                             continue;
>                         }
> 
>                         Console.WriteLine("Connected.");
> 
>                         try
>                         {
>                             await rtspClientTop.ReceiveAsync(token);
>                         }
>                         catch (OperationCanceledException)
>                         {
>                             return;
>                         }
>                         catch (RtspClientException e)
>                         {
>                             Console.WriteLine(e.ToString());
>                             await Task.Delay(delay, token);
>                         }
>                     }
>                 }
>             }
>             catch (OperationCanceledException)
>             {
>             }
>         }
> ```

You should use separate video decoders and buffers for that cameras. At the moment you have one video decoder and 2 cameras that's why you see wrong results

**Comment by ftjellal** [comment]
thanks for your answer I will try that on Monday.

**Comment by ftjellal** [comment]
Did you mean I should separate Dictionary<FFmpegVideoCodecId, FFmpegVideoDecoder>.

I try to declare new Dictionary<FFmpegVideoCodecId, FFmpegVideoDecoder> and the result is OK now.

```
private static readonly Dictionary<FFmpegVideoCodecId, FFmpegVideoDecoder> _videoDecodersMap =
            new Dictionary<FFmpegVideoCodecId, FFmpegVideoDecoder>();
private static readonly Dictionary<FFmpegVideoCodecId, FFmpegVideoDecoder> _videoDecodersMap2 =
            new Dictionary<FFmpegVideoCodecId, FFmpegVideoDecoder>();
```

Is it ok? or I should separate others?

Sry for my bad English and my dumb question.

**Comment by BogdanovKirill** [comment]
Yes, you could use separate maps and that should work

**Comment by ftjellal** [comment]
Thank you. I have finally done it. ^_^

**Comment by carlosjgr7** [comment]
podrian ayudarme estoy tengo las secuencias H264 intento convertirlas a video para poderlo transmitir, ccopio su ejemplo y me da error aqui GetDecoderForFrame()
