### ISSUE TITLE
Cache for RTSP streaming

### ISSUE THREAD

**Issue by Apache1983** [BogdanovKirill/RtspClientSharp#15]
Hi,
I have a problem with rtsp streaming from ip camera.
During the streaming I have a jerky video, is possible increase network cache?
I would like a delay of one second compared to realtime.

Thanks in advance

**Comment by BogdanovKirill** [comment]
You need to write such logic by yourself. I have no out of the box solution for you.

**Comment by Apache1983** [comment]
ok, thanks, I will try it.
Another question, in the future is possible use also codec H265?

**Comment by BogdanovKirill** [comment]
> ok, thanks, I will try it.
> Another question, in the future is possible use also codec H265?

Yes. Unfortunately I dont have device/server to implement it now

**Comment by Apache1983** [comment]
Thanks a lot :)
