### ISSUE TITLE
Build error example "RtspClientSharp.sln". No open file "avcodec.lib"

### ISSUE THREAD

**Issue by alexnur** [BogdanovKirill/RtspClientSharp#20]
Hi! Download, open example solution and build error.

VS2017, Win10 x64, Net Core 2.2. Build Solution on error:
Code: LNK1104
Description: no open file "avcodec.lib"
Project: libffmpeghelper
File: Link 
String: 1.

**Comment by Mamad4D** [comment]
i have same problem
Project: SimpleRtspPlayer
dotNet : 4.6.1

**Comment by BogdanovKirill** [comment]
Fixed. https://github.com/BogdanovKirill/RtspClientSharp/commit/bc1acd9d46ea18a9c898cd2b3c131c59c3a76735
