### ISSUE TITLE
Error playing test  TCP RTSP source :"TimedOut on receiver stream"

### ISSUE THREAD

**Issue by luguoci** [BogdanovKirill/RtspClientSharp#21]
**Error playing test RTSP source**
I use local built "Examples\SimpleRtspPlayer" and test with an online RTSP source ,result "TimedOut on receiver stream" error similar to  #2 

**To Reproduce**
1. Build example project "Examples\SimpleRtspPlayer",it run successfully
2. Input online test url"rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov" to  "device address" 
3. Had try Login & Password default or leave blank(can I leave blank if not need to login?)
4. Connecting... then Receiving frames...
5. then Get bellowing error on status bar(bottom), no pictureshow in form(still black)
```
RtspClientSharp.Rtsp.RtspClientException: Receive timeout ---> System.TimeoutException: The operation timed out.
```

**Desktop (please complete the following information):**
 - OS: Windows 10 ver1809
-  VS 2017

**Comment by luguoci** [comment]
solve it , after look insight some setting
change bolow
https://github.com/BogdanovKirill/RtspClientSharp/blob/bc1acd9d46ea18a9c898cd2b3c131c59c3a76735/Examples/SimpleRtspPlayer/GUI/ViewModels/MainWindowViewModel.cs#L74
to
```
RtpTransportProtocol.TCP
```
and work!

should have an option to select and more detail during connection fail for the example

**Comment by BogdanovKirill** [comment]
Thank you for feedback. It seems to be fixed
https://github.com/BogdanovKirill/RtspClientSharp/commit/69c9b7b29b5be8b057feea4d1d8eb436c891db17
Try 1.2.6 version

**Comment by Ghanavati7915** [comment]
I did the same And it Worked For Me . Thanks ❤
