### ISSUE TITLE
The library has no strong name

### ISSUE THREAD

**Issue by IvanovNiko** [BogdanovKirill/RtspClientSharp#23]
It is needed strong name for using in other projects signed with strong name.

When i trying to reference RtspClientSharp from project signed by strongname i have an error: Could not load file or assembly 'RtspClientSharp, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by BogdanovKirill** [comment]
I've published nuget 1.3 with sign. Please check and reopen if issue still persist

**Comment by IvanovNiko** [comment]
Kirill, hello.
I reference to new version of library and get the strong name issue yet. 
I opened the library with reflector and not show that library was signed
![image](https://user-images.githubusercontent.com/31622591/62453538-31732180-b77b-11e9-8e84-f885d6f409c0.png)

**Comment by IvanovNiko** [comment]
@BogdanovKirill and why the Architecture of new version became x86? I need AnyCPU or x64 library.

**Comment by BogdanovKirill** [comment]
Did you try nuget package from nuget.org ? It was built for Any Cpu + sign

**Comment by IvanovNiko** [comment]
Yes, i tried nuget from nuget.org. Version 1.3. 
![image](https://user-images.githubusercontent.com/31622591/62470254-b6256600-b7a2-11e9-884d-5fc0b67d730b.png)

**Comment by BogdanovKirill** [comment]
Yes, you are right. My mistake, I uploaded wrong nuget but my local version seems to be fine. Could please help to test 1.3.1 version ?

**Comment by IvanovNiko** [comment]
Yes, it is ok now in 1.3.1 version.
Thank you.

**Comment by BogdanovKirill** [comment]
Ok, thank you
