### ISSUE TITLE
I get RtspClientException: Any suitable track trying to connect to a RTSP stream

### ISSUE THREAD

**Issue by Grul-** [BogdanovKirill/RtspClientSharp#26]
Hi,

**Describe the bug**
I get `RtspClientSharp.Rtsp.RtspClientException: Any suitable track` is not found error while trying to connect to a Rtsp stream.

**To Reproduce**
I followed the example described in the [readme ](https://github.com/BogdanovKirill/RtspClientSharp/blob/master/README.md) file and put it in a console application.
I changed the `serverUri` according to my camera settings.
The following error is triggered at `await rtspClient.ConnectAsync(token.Token)` line.

**Exception message**

```
RtspClientSharp.Rtsp.RtspClientException: Any suitable track is not found
   in RtspClientSharp.Rtsp.RtspClientInternal.<ConnectAsync>d__17.MoveNext()
--- End of stack trace from previous location the exception was thrown ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in RtspClientSharp.RtspClient.<>c__DisplayClass13_0.<<ConnectAsync>b__0>d.MoveNext()
--- End of stack trace from previous location the exception was thrown ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in RtspClientSharp.RtspClient.<ConnectAsync>d__13.MoveNext()
--- End of stack trace from previous location the exception was thrown ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in rtspconsole.Program.<Main>d__0.MoveNext() in D:\Projects\rtspTest\rtspconsole\Program.cs:line 36
```

**Info:**
 - OS: Windows 10 Home 1803
 - Visual Studio: Visual Studio Community 2017 v 15.9.7
- .NET: .NET Framework 4.7.2
- C#: C# 7.3

**Additional context**
I tried to open the same stream with VLC successfully.
I also tried to change the `ConnectionParameters`, switching `RtpTransport` from TCP to UDP and switching the `RequiredTracks` to both All, Video and Audio.

**Comment by BogdanovKirill** [comment]
@Grul- 

Hello, is it possbile to give me URI to RTSP server to debug it ?

**Comment by Grul-** [comment]
Hi @BogdanovKirill, I'm sorry but I cannot give the access to the camera stream at the moment.
But I can try to capture the stream with Wireshark and I can share to you asap.

In the meanwhile, is there something else I can check?

**Comment by Grul-** [comment]
I've captured the stream on port 554 with wireshark both with the rtsp cliend and with VLC.

This is the wireshark report when I captured the stream with VLC:
![wshark_dump_vlc](https://user-images.githubusercontent.com/4226701/55900484-981a7100-5bc7-11e9-8f73-bb9f05b2f622.jpg)

And this is the wireshark report when I started my test rtsp client:
![wshark_dump_rtspclient](https://user-images.githubusercontent.com/4226701/55900594-d44dd180-5bc7-11e9-8052-6750e0b89348.jpg)

The main difference I can see is that the rtsp client stops after the `DESCRIBE` command, while the stream played with VLC continues with `SETUP` and `PLAY` commands.

**Comment by Grul-** [comment]
Hi, my problem seems related to the video encoding.
The rtsp stream with H264 video encoding works, while with H265 gives me the above issue.

**Comment by BogdanovKirill** [comment]
@Grul- 

Sorry, but H.265 is not supported now

**Comment by Grul-** [comment]
Ok, the support to H265 is not an issue now. I checked the camera configuration and I noticed that the stream was H265 encoded. 
So everything works fine at the moment, thanks for the fast replies!
