### ISSUE TITLE
How can i get RawJpegFrame type frames?

### ISSUE THREAD

**Issue by wangning08115** [BogdanovKirill/RtspClientSharp#28]
rtspClient.FrameReceived += (sender, frame) 

the paras frame type is always = RtspClientSharp.RawFrames.Video.RawH264IFrame
But you need "frame is RawJpegFrame",
How can i get RawJpegFrame type frames?
I connect the RTSP address.

        private static async Task MakeSnapshotsAsync(Options options, CancellationToken token)
        {
            try
            {
                if (!Directory.Exists(options.Path))
                    Directory.CreateDirectory(options.Path);

                int intervalMs = options.Interval * 1000;
                int lastTimeSnapshotSaved = Environment.TickCount - intervalMs;

                var connectionParameters = new ConnectionParameters(options.Uri);
                using (var rtspClient = new RtspClient(connectionParameters))
                {
                    rtspClient.FrameReceived += (sender, frame) =>
                    {
                        **if (!(frame is RawJpegFrame))
                            return;**

                        int ticksNow = Environment.TickCount;

                        if (Math.Abs(ticksNow - lastTimeSnapshotSaved) < intervalMs)
                            return;

                        lastTimeSnapshotSaved = ticksNow;

**Comment by BogdanovKirill** [comment]
Hi,

Your RTSP server (camera) should be adjusted to send JPEG stream. Check your settings

**Comment by wangning08115** [comment]
oh, thanks.
If the camera use RawH264IFrame,  The can i  MakeSnapshots Directly？
Or  can i  MakeSnapshots use Pure C# code.   Because i want reduce my program size, The ffmpeg Lib is bigger.

**Comment by BogdanovKirill** [comment]
If you have H.264 stream, then you have to re-encode it to JPEG. You can't do that without decoder-encoder pair. That's why you need FFmpeg library or something else.

**Comment by wangning08115** [comment]
thanks.
