### ISSUE TITLE
RTSP to HTTP

### ISSUE THREAD

**Issue by bartekkois** [BogdanovKirill/RtspClientSharp#29]
Is is possible using your library to connect from ASP .NET Core controller to RTSP stream from IP camera and return HTTP video stream compatible with HTML5 <video> tag?

**Comment by BogdanovKirill** [comment]
No, it is impossible.This library could give you only compressed stream and you have to repack it to browser compatible format by yourself

**Comment by Feofilakt** [comment]
Здравствуйте. Вот здесь https://flashphoner.com/transliruem-webrtc-rtsp-i-rtmp-potoki-na-media-source-extensions/?lang=ru (RTSP to MSE) написано: 

> IP камера, как правило, нативно поддерживает H.264 и AAC кодеки, поэтому кодеки полностью совпадают с теми, что используются на MSE. Это помогает избежать транскодинга, поглощающего ресурсы CPU.

То есть можно записывать фреймы в Websockets и отправить прямо в браузер, если они в H.264?
