### ISSUE TITLE
Change language of donation link

### ISSUE THREAD

**Issue by tinohager** [BogdanovKirill/RtspClientSharp#3]
I do not understand Russian.

lc=RU change lc=EN

**Comment by BogdanovKirill** [comment]
Thank you, I didnt know. Should be fixed now.

**Comment by tinohager** [comment]
not work is russian again... i am use paypal.me -> https://www.paypal.me/

**Comment by tinohager** [comment]
now it works fine

**Comment by BogdanovKirill** [comment]
Great, thank you
