### ISSUE TITLE
System Handles not being released

### ISSUE THREAD

**Issue by TomCat666** [BogdanovKirill/RtspClientSharp#30]
Hello

Since I am using 5 video streams at once which are being used for a long period of time (8 or more hours) I am getting an error that the system ran out of Handles. You can see this if you add the "Handles" column in the Task Manager. They are going up pretty quickly, in about 3 hours of 5 video streams they go from 300 to about 20.000 here. If I stop the videos they are not released either so it seems there is a leak of Handles somewhere. I tried debuging this and looking in the performance monitor, but was unable to find exactly where they leak. This is the error I get after the system runs out of handles:

Error: RtspClientSharp.Rtsp.RtspClientException: Receive error ---> System.ComponentModel.Win32Exception: The current process has used all of its system allowance of handles for Window Manager objects
   at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32 dwExStyle, String lpszClassName, String lpszWindowName, Int32 style, Int32 x, Int32 y, Int32 width, Int32 height, HandleRef hWndParent, HandleRef hMenu, HandleRef hInst, Object pvParam)
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Imaging.WriteableBitmap.SubscribeToCommittingBatch()
   at System.Windows.Media.Imaging.WriteableBitmap.Unlock()
   at System.Windows.Media.Imaging.WriteableBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat, BitmapPalette palette)
   at RealTimeVideo.handleFrame(RawFrame frame)

**Comment by TomCat666** [comment]
Ok, it was actually an issue because of the WriteableBitmap. For some reason it sometimes didn't release the handle and they started piling up. Now I am using normal Bitmap and everything is fine, Handles stay stable over a longer period of time.

**Comment by BogdanovKirill** [comment]
Hello,

Hm, it's very interesting issue. I would like to investigate. Could you check this bug on other machines? (different OS, different .NET version)

**Comment by BogdanovKirill** [comment]
Could you also check code from master branch? Thank you

**Comment by BogdanovKirill** [comment]
It seems that you create new WriteableBitmap per frame. If it's true, you shouldn't do like this. Please always reuse it (see SimpleRtspPlayer in examples, mater branch) or performance will be decreased significantly

**Comment by TomCat666** [comment]
Hi. 

Yeah, even on SimpleRtspPlayer the Handles go up through the day if I leave 5 streams running (5 players). They don't go up so much, from around 500 to around 1000. 
And you were right, I was creating a new WriteableBitmap every frame before (I copy pasted old code which did that). Now I am doing this differently and Handles stay fixed through the day, no more leaks.

**Comment by BogdanovKirill** [comment]
I tested SimpleRtsPlayer (master branch) this weekend and did not find any leaks. 
Could we close this?

**Comment by TomCat666** [comment]
Yes, no leaks anywhere anymore. Thank you !

**Comment by rubensmarcondes** [comment]
@TomCat666 can you give me an idea, code sample? I have a problem to convert the frame to bitmap... When I put one camera I can convert the h264 to jpeg but when I have more than one in threads I get an error... Could you help me?

**Comment by TomCat666** [comment]
Sure...

when the first frame comes in create a normal Bitmap:

int width = decodedVideoFrame.Width;
int height = decodedVideoFrame.Height;

Bitmap b = new Bitmap(width, height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);

Decode is then:

var bitmapData = b.LockBits(new Rectangle(0, 0, width, height), System.Drawing.Imaging.ImageLockMode.WriteOnly, System.Drawing.Imaging.PixelFormat.Format24bppRgb);
var length = decodedVideoFrame.Stride * b.Height;
Marshal.Copy(decodedVideoFrame.DecodedBytes.Array, 0, bitmapData.Scan0, length);
b.UnlockBits(bitmapData);

**Comment by rubensmarcondes** [comment]
I see... but the error I get is with the decoder!
Did you need to do many changes in the original project to accept many cameras ? What you called "decodedVideoFrame"

**Comment by TomCat666** [comment]
You need to have a separate RealtimeVideoSource for each camera. When you have that you use it to decode the video frame first (this is inside the FrameReceived Handler that you use (I just copied the ConnectAsync method from the SampleMoviePlayer) :

IDecodedVideoFrame decodedVideoFrame = _realtimeVideoSource.GetDecodedVideoFrame(frame);

Then you do the steps in my previous post...
