### ISSUE TITLE
Recording the stream in pieces to a files of the desired length

### ISSUE THREAD

**Issue by fotels** [BogdanovKirill/RtspClientSharp#31]
Thank you for this RTSP client, it's really amazing. I admire the enormity of the work you have put into creating this project.

For a few days, I have been trying to expand its capabilities to record video from the camera to video files in pieces of, for example, 1 minute length. My point is that instead of live view, I would like to define the target length of the files, and then let the program record the RTSP stream to files dividing it into given time periods. Thanks to this, I could later easily archive and then analyze the recordings.

Forgive me if this is a trivial problem, but unfortunately I can not deal with it. I hardly managed to save a single frame to a PNG file, but it is rather inefficient and it is hardly possible to put them in a movie. It would be a slide show rather than a movie...

Can I ask for help in this task?

**Comment by BogdanovKirill** [comment]
Hello,

Thank you for your feedback. You could write all frames from RTSP client to you own file format and then simply read it again from file.

**Comment by BogdanovKirill** [comment]
Discussion currently is here: https://github.com/BogdanovKirill/RtspClientSharp/issues/34
Please reopen if required
