### ISSUE TITLE
Buffer is reached maximum allowed size

### ISSUE THREAD

**Issue by rubensmarcondes** [BogdanovKirill/RtspClientSharp#32]
Hi, when i try to connect to my camera i get this error... 
I, actualy, have other cameras and the others works fine... but one of them give me this error... 

On VLC i have this configuration:
![image](https://user-images.githubusercontent.com/39574096/58345415-aeeeed00-7e2e-11e9-9341-0bac66e5222d.png)

The main difference between the cameras is the resolution and the frames rate.. this one is 25 and the others 15

RtspClientSharp.Rtsp.RtspClientException: Receive error ---> RtspClientSharp.MediaParsers.BufferOverflowException: Buffer is reached maximum allowed size
   em RtspClientSharp.Utils.ElasticBuffer.AddBytes(ArraySegment`1 byteSegment)
   em RtspClientSharp.MediaParsers.H264VideoPayloadParser.ParseFU(ArraySegment`1 byteSegment, Int32 donFieldSize, Boolean markerBit)
   em RtspClientSharp.MediaParsers.H264VideoPayloadParser.Parse(TimeSpan timeOffset, ArraySegment`1 byteSegment, Boolean markerBit)
   em RtspClientSharp.Rtp.RtpStream.ProcessImmediately(RtpPacket& rtpPacket)
   em RtspClientSharp.Rtp.RtpStream.Process(ArraySegment`1 payloadSegment)
   em RtspClientSharp.Rtsp.RtspClientInternal.<ReceiveOverTcpAsync>d__34.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em RtspClientSharp.Rtsp.RtspClientInternal.<ReceiveAsync>d__19.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em RtspClientSharp.RtspClient.<ReceiveAsync>d__14.MoveNext()
   --- Fim do rastreamento de pilha de exceções internas ---
   em RtspClientSharp.RtspClient.<ReceiveAsync>d__14.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em MjpegSnapshotsMaker.Program.<MakeSnapshotsAsync>d__2.MoveNext() na C:\temp\RtspClientSharp-master_v4\Examples\MjpegSnapshotsMaker\Program.cs:linha 189

**Comment by BogdanovKirill** [comment]
Hi,

Could you download master branch, compile and check again?

**Comment by rubensmarcondes** [comment]
Hi!! It seems to work fine! Thank you very much!
