### ISSUE TITLE
v380 camera RTSP stream bug 

### ISSUE THREAD

**Issue by TomCat666** [BogdanovKirill/RtspClientSharp#36]
Hello

I bought a new (cheap, chinese) camera which has RTSP stream supported. The stream works fine with VLC and other players, unfortunetly I get a timeout error in RtspClientSharp after a succesfull connection... I tried debugging for a day but unfortunetly couldnt fix it myself. 
I put the stream available on the net... please send me an email to tomcat@sgn.net  and I will provide the url to the stream if you would please try and debug/support it.

Bestr regards,
Tomaz

**Comment by BogdanovKirill** [comment]
Thank you for report. Fixed in master branch
https://github.com/BogdanovKirill/RtspClientSharp/commit/712083b2ad241901eb9200da361cc39c01ea69eb
Fix will be available later in nuget

**Comment by TomCat666** [comment]
Thank you very much Kirill !!!

**Comment by BogdanovKirill** [comment]
I've pulished nuget 1.3. Reopen if requried
