### ISSUE TITLE
If use h265,will throw error

### ISSUE THREAD

**Issue by wangning08115** [BogdanovKirill/RtspClientSharp#37]
If use h265 , will throw error,
When h265, below code will found no RtspMediaTrackInfo in function GetTracksToSetup().
and next will throw error: 
RtspClientSharp.Rtsp.RtspClientException: 'Any suitable track is not found'

   private IEnumerable<RtspMediaTrackInfo> GetTracksToSetup(IEnumerable<RtspTrackInfo> tracks)
        {
            foreach (RtspMediaTrackInfo track in tracks.OfType<RtspMediaTrackInfo>())
            {
                if (track.Codec is VideoCodecInfo && (_connectionParameters.RequiredTracks & RequiredTracks.Video) != 0)
                    yield return track;
                else if (track.Codec is AudioCodecInfo &&
                         (_connectionParameters.RequiredTracks & RequiredTracks.Audio) != 0)
                    yield return track;
            }
        }

![image](https://user-images.githubusercontent.com/3455705/61045974-994d7b00-a40e-11e9-86cb-9420023a9b4e.png)

**Comment by BogdanovKirill** [comment]
H265 is not supported.
duplicate https://github.com/BogdanovKirill/RtspClientSharp/issues/17
