### ISSUE TITLE
NetworkClientFactory initialization causes exception on some platforms

### ISSUE THREAD

**Issue by tfsJoe** [BogdanovKirill/RtspClientSharp#38]
**Describe the bug**
On some platforms, Initializing Socket.Buffer to 0 causes the following exception:
`RtspClientSharp.Rtsp.RtspClientException: Connection error ---> System.ArgumentException: Value does not fall within the expected range.`

Commenting out the referenced line seems to fix the issue. Currently, this is line 15 of NetworkClientFactory.cs.

This may be related to the implementation of System.Net.Sockets.Socket in the .NET equivalent in the Apple ecosystem. This issue does not occur on Windows.

**To Reproduce**
This occurred in a project which integrates RtspClientSharp in Unity. It ran without issue on Windows, but failed on Mac and in a build for tvOS.

1. Place the code into a Unity project
2. Wrap the code in a MonoBehavior
3. Press play and run the MonoBehavior

(Please note the above steps are already completed in [this test repo I made for this issue)](https://github.com/tfsJoe/RtspSharpUnity/)

When the initialization runs an exception will be thrown and should be caught in the Debug log.

**Expected behavior**
Successfully initialize the socket and continue with program execution

 - Device: MacBook Air, build also attempted for Apple TV
 - OS: macOS Mojave  10.14.5, tvOS 12.3
 - Browser N/A
 - RtspClientSharp v1.2.8
 - Unity 2018, Unity 2019

**Additional context**
Unity on Mac uses Mono, and states it is ".NET 4.5 equivalent" - I am unsure if this is related.

**Comment by BogdanovKirill** [comment]
Hello,

Thank you for report. I should add some checks for platform before modifying send buffer size.

**Comment by tfsJoe** [comment]
Just a note on your fix, I think you will run into the issue on tvOS as well (AppleTV), and likely iOS also.

**Comment by BogdanovKirill** [comment]
@tfsJoe 

Could you help me to check it ? I suppose that Environment.OSVersion.Platform will be equal to PlatformID.MacOSX on tsOS/iOS

**Comment by tfsJoe** [comment]
OK, I will bring in this change and take a look.

----- Original Message -----

**Comment by tfsJoe** [comment]
I have an AppleTV to test with, but no iOS device. However, I just made a build and tested it. Unfortunately it failed, and strangely, the value I got for `Environment.OSVersion.Platform` was `PlatformID.Unix`!

**Comment by BogdanovKirill** [comment]
Thank you for help. For now I see only one safe way: remove this line with buffer size completely from code

**Comment by BogdanovKirill** [comment]
If this one fix is ok I will publish new nuget

**Comment by tfsJoe** [comment]
Ok, thanks for giving it attention. I'm away from my device now but I will test it again in a few hours.On Jul 17, 2019 2:26 AM, Kirill <notifications@github.com> wrote:If this one fix is ok I will publish new nuget

**Comment by tfsJoe** [comment]
This was ok for me!
