### ISSUE TITLE
Install-Package RtspClientSharp - Not supported

### ISSUE THREAD

**Issue by FishBlubCP** [BogdanovKirill/RtspClientSharp#41]
Install-Package : Could not install package 'RtspClientSharp 1.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but
 the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package RtspClientSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by BogdanovKirill** [comment]
Hi ! You need to use newer framework (e.g. .NET Framework 4.6.1) that supports .NET Standard 2.0
