### ISSUE TITLE
H264Parser - ProcessNalUnit generateFrame parameter always false

### ISSUE THREAD

**Issue by Dimigergo** [BogdanovKirill/RtspClientSharp#43]
Hello!

In the `ProcessNalUnit` method the last parameter (generateFrame) is always false.
In this case the following condition is always false in H264Parser.cs - line 143:
`if (generateFrame && _frameStream.Position == 0)
TryGenerateFrame(byteSegment, mediaId);`

Is it a bug, or it is an old code?

Thanks in advance!

**Comment by BogdanovKirill** [comment]
Why do you think that it's a bug? It depends on rtsp source. It seems that in your case it is always false, but it doesn't mean that it will be false always

**Comment by Dimigergo** [comment]
Ok, but the there are 2 method calls:
H264Parser.cs - line 107 `ProcessNalUnit(mediaId, byteSegment, true, false);`
H264Parser.cs - line 50 `ProcessNalUnit(byteSegment, false, false);`

Both of them are hard-coded false.

**Comment by BogdanovKirill** [comment]
Thank you for your report. You are right. Should be fixed now.
