### ISSUE TITLE
60 fps stream like 1 fps

### ISSUE THREAD

**Issue by JeremiSharkboy** [BogdanovKirill/RtspClientSharp#49]
**Describe the bug**
So, im using your lib to display my RTSP stream 60 fps. But i can see only 1 frame per second. Other players like vlc or mpc can display this 60 frames. Where is problem, how can i increase it?

**Comment by BogdanovKirill** [comment]
It's difficult to understand where problem is from your description. Do you have enough powerful CPU to decode H.264 ? VLC could use hardware decoding with GPU.

**Comment by JeremiSharkboy** [comment]
I think i7 8 gen is enough for decode this.
I found out that an error occurs at FrameReceived event at RealtimeVideoSource.cs: 56
`  IDecodedVideoFrame decodedFrame = decoder.TryDecode(rawVideoFrame);`
return null every 59 frame, 

later i got that 
`FFmpegVideoPInvoke.DecodeFrame()`
return status code -3 on this frames

**Comment by BogdanovKirill** [comment]
Could you give me direct access to your device? You could mail me to bogdanov.kv@bk.ru

**Comment by kenrentz** [comment]
I am also experiencing this issue on one of our cameras. It is an Axis Q1755 network camera. Our other cameras including some Axis models work fine. This particular camera is showing the exact same 1 fps behavior with the return code of -3. This camera appears to display correctly using the ffplay program. Please let me know if you need any additional information.

**Comment by BogdanovKirill** [comment]
hello,
I need access to camera

**Comment by BogdanovKirill** [comment]
@kenrentz 
Thank you very much for acces to camera. It seems that poblem was resolved.

Guys, could you check 1.3.3 version please ?
