### ISSUE TITLE
Thank you !! But Examples 64Bit OS Not Work T_T

### ISSUE THREAD

**Issue by BBUBBA** [BogdanovKirill/RtspClientSharp#6]
It's Good Project !!

my project use this project and Opencvsharp.

But i need fast Image processing.

I Tested processing Time.

opencv function is So fast on 64bit process.

But "libffmpeghelper" is 32Bit Option.

how can i use on 64bit OS???

**Comment by BBUBBA** [comment]
Solve !!!

1. ffmpeg Include and lib file change (x64)
2. Compile.
3. Good work^^

Thank you ^^!!!

**Comment by BogdanovKirill** [comment]
Nice

**Comment by nicolasprieto91** [comment]
@BBUBBA do u have the 64x libffmpeghelper.dll??

**Comment by OptivolveAtila** [comment]
@BBUBBA do you have the 64x libffmpeghelper.dll?
