### ISSUE TITLE
Transform Raw264Frame to Jpeg byte[]

### ISSUE THREAD

**Issue by ramonmpa** [BogdanovKirill/RtspClientSharp#60]
I'm trying to transform a Raw264Frame to Jpeg format byte array, but don't know which class should I use for this. 
In my case I have to take a picture of the camera stream and save as jpeg file.

Do you know how to transform a Raw264Frame to a Jpeg byte[]?

Thanks in advance!

For testing purpose I'm using this public rtsp url: rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen03.stream

**Comment by RandDruid** [comment]
The easiest way is to take SimpleRtspPlayer example, go to VideoView.xaml.cs, function Invalidate. It writes every new frame to WriteableBitmap. You can save it to disk as described in https://stackoverflow.com/questions/17140774/how-to-save-a-writeablebitmap-as-a-file

**Comment by ramonmpa** [comment]
Thank you so much RandDruid!
