### ISSUE TITLE
SimpleRTSPPlayer not playing

### ISSUE THREAD

**Issue by imtrobin** [BogdanovKirill/RtspClientSharp#69]
Trying the RTSPSimplePlayer on this wowza sample stream, no video plays and the Receive throws timeout exception

rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

Stream is working with vlc. Window 10, desktop.
Lastest fresh pull from github.

**Comment by BogdanovKirill** [comment]
I don't see any problem, your link works in player. Try to set TCP to RtpTransport property in connection parameters.

**Comment by BogdanovKirill** [comment]
Try to change solution platform from Any Cpu to x86 or x64.
UDP could not work because of firewall and/or packet loss.

**Comment by imtrobin** [comment]
Ok, changed to x64, working with link both TCP and UDP. Thanks!

**Comment by cdslily** [comment]
I have the same issue, I made the following changes in sample。No sign-in required。
//connectionParameters.RtpTransport = RtpTransportProtocol.UDP;  default is TCP
 connectionParameters.CancelTimeout = TimeSpan.FromSeconds(15);
Status prompt receive timeout。

here's a tracked TCP stream using wireshark's catch bag。

OPTIONS rtsp://192.168.88.83:8554/channel=0 RTSP/1.0
CSeq: 1
User-Agent: RtspClientSharp

RTSP/1.0 200 OK
CSeq: 1
Date: Tue, Jan 07 2020 01:56:24 GMT
Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER

DESCRIBE rtsp://192.168.88.83:8554/channel=0 RTSP/1.0
CSeq: 2
User-Agent: RtspClientSharp
Accept: application/sdp

RTSP/1.0 200 OK
CSeq: 2
Date: Tue, Jan 07 2020 01:56:24 GMT
Content-Base: rtsp://192.168.88.83:8554/channel=0/
Content-Type: application/sdp
Content-Length: 533

v=0
o=- 1578362184032874 1 IN IP4 192.168.88.83
s=H.264 Video, streamed by the EasyIPCamera v1.3.16.1206
i=channel=0
t=0 0
a=tool:LIVE555 Streaming Media v2016.04.01
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:H.264 Video, streamed by the EasyIPCamera v1.3.16.1206
a=x-qt-text-inf:channel=0
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:1048576
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=Z2QAKKy0A8ARPywgAAADACAAAAUR4wZU,aO88sA==
a=control:track1
SETUP rtsp://192.168.88.83:8554/channel=0/track1 RTSP/1.0
CSeq: 3
User-Agent: RtspClientSharp
Transport: RTP/AVP/TCP;unicast;interleaved=0-1

RTSP/1.0 200 OK
CSeq: 3
Date: Tue, Jan 07 2020 01:56:24 GMT
Transport: RTP/AVP/TCP;unicast;destination=192.168.88.88;source=192.168.88.83;interleaved=0-1
Session: 6F3C2B4E;timeout=65

PLAY rtsp://192.168.88.83:8554/channel=0/ RTSP/1.0
CSeq: 4
User-Agent: RtspClientSharp
Session: 6F3C2B4E
Range: npt=0.000-

RTSP/1.0 200 OK
CSeq: 4
Date: Tue, Jan 07 2020 01:56:24 GMT
Range: npt=0.000-
Session: 6F3C2B4E


$..8..........c...p..v....................DESKTOP-FVH29O3...$........v......A.F!.................D..)...@|..2..k.	9'..Z...x.....A.?..b......}.......$.AQoe....... .....&p....!....A...i....@......}..&......$.~...D......A....F!7..X..i..`..
B.4.2.......$..".....v......A.f!......T...{.D..Q
.<&.3..4..U.)R.........Qv.i..D.........h......o@{..A.o..`.....A.?..b...8@ W...#.^.t...JU".zfw
`m.3Peh~p.F.*.}y.@/j...q...-........ ...L..Kl......A...i.._.X..
...R...+.....l._+.h.{.c..$.....Z.....A....f!w.............b.T.;r.....|Z.......}.|j.../  
And then there's a lot of data.
