### ISSUE TITLE
Q For Token(Authorization)

### ISSUE THREAD

**Issue by ygxw** [BogdanovKirill/RtspClientSharp#7]
HI,

i had try u program is very good.
but i have a question. how can i set not authorized.
ex: i use a url authorization( rtsp://admin:admin@127.0.0.1:554 )   or   not authorized rtsp(like:  rtsp://127.0.0.1:554/1.sdp )

thx.

**Comment by BogdanovKirill** [comment]
Hi,

Can't understand your question. Do you mean that you want to connect without login and password ? If yes why not to use rtsp://127.0.0.1:554/1.sdp as url ?

**Comment by BogdanovKirill** [comment]
Could you check VLC player please ? Does it work well in that case ?

**Comment by ygxw** [comment]
yes，same url，i check for vlc and emgucv is ok。

（for my code，may be have any question？）

**Comment by BogdanovKirill** [comment]
Could you give me access to your camera I will check for bug

**Comment by ygxw** [comment]
i just try same code. all is ok, i don't know why.
may be my rtsp server problem?

thx.
