### ISSUE TITLE
RTSP Frame Grab of H264 Example

### ISSUE THREAD

**Issue by inzi** [BogdanovKirill/RtspClientSharp#8]
I've been unsuccessful in capturing individual rawframes to images when the stream is H264, like the example that uses MJPEG. I know the FFMpeg library is capable of doing it because I've been able to use the executable to pipe the results to individual files.

In examining the SimpleRTSPClient, I can see how the client is providing the rawframe into the event handler.

From there - I see in the example SimpleRtspPlayer, the RealTimeVideoSource.cs class handles the raw frame, the leans on ImageUtils to construct a buffer.

This is where I get confused. In the MJpeg Snapshot maker example, it simply grabs the FrameSegment.

Handling of other codes in the snapshot maker example would be helpful to understand how to process streams. 

I've tried taking the raw stream and saving it, but the resulting files are not image files.

I would like to suggest an example snapshot maker that supports the other codecs.

If I can make mine work, I'll contribute it as an example.

**Comment by BogdanovKirill** [comment]
Hello,
May be I dont understand the source of your problem, but you cant save h264 stream as individual decodable frames. You must decode all frames and then encode them for example in jpeg format (transcoding)

**Comment by BogdanovKirill** [comment]
Take a look at SimpleRtspPlayer, here you could see how to decode H264 frames to bitmaps. You could use standard jpeg encoder in .net to get jpeg from bitmap.

**Comment by inzi** [comment]
Thank you for the tips- this is what I'm trying to learn more about. I do apologize for my naive questions, but I'm learning about this - Thank you for creating project, too, by the way. I'm learning a lot.

In the SimpleRtsPlayer - The RealtimeVideoSource.cs class seems to do the lifting of frames, am I correct in that?  It looks like it creates an FFmpegVideoDecoder for a frame (held in the Decoders map dictionary), and when a frame arrives, it then gets the parameters of the frame (width and size) by calling the TryDecode.

Then, it looks to setup a parameters to match the resolution of the stream, creates a memory buffer that will match a "full frame" (I am understanding this correctly?), then finally, it goes back to the decoder to get a decoded frame. 

At this point - is the decodedFrame a complete frame that is then used on the GUI? In other words, is that a bitmap at that point that could then be saved in BMP format or converted to an image? 

Is your strategy here to create the FFmpeg decoder object for the stream, and then have it process the data received from the RTSP source, and then keep the decoder object alive so it can then assemble the frames into an image?

This is super fun to learn about, so thank you again.

**Comment by inzi** [comment]
I sent you a small donation for your efforts and kind support.

**Comment by BogdanovKirill** [comment]
> Thank you for the tips- this is what I'm trying to learn more about. I do apologize for my naive questions, but I'm learning about this - Thank you for creating project, too, by the way. I'm learning a lot.

It's ok, you are welcome.

> In the SimpleRtsPlayer - The RealtimeVideoSource.cs class seems to do the lifting of frames, am I correct in that? It looks like it creates an FFmpegVideoDecoder for a frame (held in the Decoders map dictionary), and when a frame arrives, it then gets the parameters of the frame (width and size) by calling the TryDecode.

Yeah, that's it!

> Then, it looks to setup a parameters to match the resolution of the stream, creates a memory buffer that will match a "full frame" (I am understanding this correctly?), then finally, it goes back to the decoder to get a decoded frame.

The main idea here is that we have display area (window) of a certain size where we want to draw video stream. In general frame size is not equal to display area size, that's why we must use scaling when decoding process is finished. For you it means that you could get for example full hd h264 video from RTSP server and then rescale it to 720p or something else.

> At this point - is the decodedFrame a complete frame that is then used on the GUI? In other words, is that a bitmap at that point that could then be saved in BMP format or converted to an image?

Yes, decoded frame is equal to complete bitmap and you could easily create .net bitmap. See here: https://stackoverflow.com/questions/6782489/create-bitmap-from-a-byte-array-of-pixel-data

> Is your strategy here to create the FFmpeg decoder object for the stream, and then have it process the data received from the RTSP source, and then keep the decoder object alive so it can then assemble the frames into an image?

Yes you are right. We should keep decoder alive for several reasons: 1) it has state which is taken into account in the decoding process of H.264 2) performance

> This is super fun to learn about, so thank you again.

Great, thank you too.

**Comment by BogdanovKirill** [comment]
> I sent you a small donation for your efforts and kind support.

Thank you very much for your support!

**Comment by BogdanovKirill** [comment]
At the weekend I can help you to get bitmaps from decoded frames effectively

**Comment by inzi** [comment]
Hey, thank you! I'll try and create a project that mimics the MjpegSnapshotsMaker based on the project - It might prove useful to someone else. 

I'll update here on my progress.

**Comment by inzi** [comment]
I've created a project - I am still trying to get it to work - but thoughts on this so far?

I've added you as a collaborator.

My thinking was to create a class that this handed the frame off to, that would then convert to an image and save it asynchronously, allowing the processing not to block the next incoming frame.

This class would work with a dictionary of transcoders to output the file.

Thoughts?

**Comment by inzi** [comment]
BTW - I'm trying to make this work in Core - I think that'd be cool.

**Comment by BogdanovKirill** [comment]
@inzi
Tomorrow I will help you to make it

**Comment by inzi** [comment]
Thanks! I think I've made some progress

**Comment by inzi** [comment]
I'm learning so much about c# from this project - I just wanted to say thanks again.  This is teaching me a lot about threading, overloads, and event handling.

**Comment by inzi** [comment]
I don't think this works with core - I'm going to try another project. I am working towards converting the ReatTime video class that will simply save the file.

Before I do that, I'm going to try and modify the simple player to save each frame - so understand where to do that.

**Comment by BogdanovKirill** [comment]
> I don't think this works with core - I'm going to try another project. I am working towards converting the ReatTime video class that will simply save the file.

No, it works on net core. But you should understand that it depends on ffmpeg libraries which are unmanaged and should be compiled appropriately for every platform

>Before I do that, I'm going to try and modify the simple player to save each frame - so understand where to do that.

I need push access to your repository, I will give you an out of the box example.

**Comment by BogdanovKirill** [comment]
Check here:
https://github.com/inzi/rtspcapture/commit/bdfaea3eff8cd286082814e9f1e820a93e98aa41

**Comment by inzi** [comment]
I was able to do it yesterday! The github crash didn’t let me post. I’ll post the other project so you can look at it.

I’ll investigate building FFMPEG into unmanaged DLLs to make it work with core.

**Comment by inzi** [comment]
So - maybe you would know  - I tried using the x86 dlls in your project with core but it doesn't like them.

I tried disabling managed code check. Like this:

        [DllImport(LibraryName, EntryPoint = "create_video_decoder", CallingConvention = CallingConvention.Cdecl), SuppressUnmanagedCodeSecurity]


but still doesn't work. 

It throws: 

RtspClientSharp.Rtsp.RtspClientException: Receive error ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

I'm trying to run the core app under Windows 10 in Visual Studio.

Any ideas? 

I'm going to try the tool media-autobuild_suite-master to build FFMPEG and use the DLLs, but I am not sure what I'm doing! haha. :)

**Comment by BogdanovKirill** [comment]
> I'd make this branch yesterday ("working") - https://github.com/inzi/rtspcapture/tree/Working
> 
> It's similar to your code - maybe it looks better for someone like me learning the process?
> 
> That branch is greatly cleaned up. If you think it's worthy anything for someone else to look at, I'll put it into it's own repo .

Looks good. I will give link to your repo if somebody do something similar.

**Comment by BogdanovKirill** [comment]
You need to compile libffmpeghelper under x64 platform. You don't need to compile FFmpeg by yourself, just get it here: https://ffmpeg.zeranoe.com/builds/ (Dev)

**Comment by BogdanovKirill** [comment]
Also I want to add that you could download x86 net core runtime from official site and start your program in console. Make sure that you call x86 version of dotnet executable.

**Comment by inzi** [comment]
I will merge Working into master so the code is cleaner

**Comment by inzi** [comment]
Can libffmpeghelper be compiled for linux-arm so it can be used on a linux machine?

**Comment by BogdanovKirill** [comment]
> Can libffmpeghelper be compiled for linux-arm so it can be used on a linux machine?

Sure. But you should have powerful enough ARM CPU to decode H264 stream. Perhaps you should find SDK for your processor to do hardware decoding.

**Comment by BogdanovKirill** [comment]
Hello, any news ?

**Comment by BogdanovKirill** [comment]
It seems that your problems were solved

**Comment by noumanqaiser** [comment]
HI Inzi and BogdanovKirill,

Hi Team,
I was following your conversation and it seems you have done a great piece of work for frame capturing from RTSP streams. I see that you created the project in the link below for this purpose.

https://github.com/inzi/rtspcapture

Within this, I see that the code for RTSP frame capture is different in master and Working branches. Can you confirm if the final piece of code for frame capturing is the one in working branch:

https://github.com/inzi/rtspcapture/blob/Working/RTSPSnapshotMaker/Program.cs

Regards,
Nouman

**Comment by aungsanwin** [comment]
I definitely learn a lot from your discussion. I am not sure my question will be of your interest. How do we extract meta data information from RTSP frame?
