### ISSUE TITLE
Response is too large

### ISSUE THREAD

**Issue by bartengine27** [BogdanovKirill/RtspClientSharp#97]
Dear,

  I wrote an ASP.NET Core controller to stream a video:

`
    public class VideoStreamController : Controller
    {
        [Microsoft.AspNetCore.Mvc.Route("videostream/index")]
        [Microsoft.AspNetCore.Mvc.HttpGet]
        public IActionResult GetVideoContent()
        {            
            return File(System.IO.File.OpenRead(@"C:\temp\Video_1.mp4"), "video/mp4", true);            
        }
    }
`

When I try to open http://localhost/videostream/index I get a "Response is too large" error message in SimpleRtspPlayer.

  Any idea how I can start debugging this?

Thanks,
Bart

**Comment by danielshea7** [comment]
I am having the same issue. Did you find anything? Thank you

**Comment by Dimigergo** [comment]
Some camera, mine too, immediately start sending the frames after PLAY request. The PLAY response process read bytes from the stream but in this case more than 8 KB bytes received (frame bytes and PLAY response somewhere) (f.:e.: 40 KB).
The workaround is: change the `Constants.MaxResponseHeadersSize` from 8 * 1024 to 64 * 1024. It will be enought, but if not than higher value.

I don't know what is the perfect solution, but it is work for me, if your problems are the same as mine.
